services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "8000:80"
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  frontend:
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://localhost:8000
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
    depends_on:
      backend:
        condition: service_healthy
